services:
  cdn:
    image: eacer/simple-cdn-service:250922
    ports:
      - "8888:80"
    environment:
      SERVER_NAME: cdn.local
      ALLOWED_LAN: 192.168.99.0/24
    volumes:
      - ./static:/usr/share/nginx/html:ro